[package]
name = "async_file_hasher"
version = "0.1.0"
edition = "2021"

[lib]
name = "async_file_hasher"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "async_file_hasher"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
md5 = "0.7"